### ISSUE TITLE
”content“ 字段为None有引起的错误

### ISSUE THREAD

**Issue by vank3f3** [Huoyuuu/SearchGPT-Explorer#1]
![image](https://github.com/Huoyuuu/SearchGPT-Explorer/assets/47717461/1f03e839-6dc6-46f4-8895-980f3dbc2a06)
版本说明：
Python：3.8
OpenAI：0.27.8
错误说明：在search_gpt_core 中第 94 行，”response_message.model_dump()“ 在生成新的message对象时，会因为 ‘contest’ 为空而导致OpenAI 报错。

**Comment by vank3f3** [comment]
补充一下，openai 版本为1.35.12
![image](https://github.com/Huoyuuu/SearchGPT-Explorer/assets/47717461/ba0f4fb4-2f5f-4928-a16e-7523e69db249)
断点
![image](https://github.com/Huoyuuu/SearchGPT-Explorer/assets/47717461/d648cbcf-97b7-4171-aa75-a9aba5c877db)

**Comment by Huoyuuu** [comment]
尝试了一下，没能成功复现，把openai库更新到最新版本后仍然没有遇到问题，本地的测试结果还是可以正常运行的，这个还是挺难去调试的，我想想，我下面先分两个方面去回复。

第一个是API可以正常运行吗？用下面的测试代码调试一下，确认可以正常返回信息。
```python
from openai import OpenAI
import os

# 设置API密钥和基础URL
API_KEY = os.getenv(f"OPENAI_API_KEY")
BASE_URL = os.getenv(f"OPENAI_BASE_URL")
MODEL_NAME = "gpt-4o"

client = OpenAI(api_key=API_KEY, base_url=BASE_URL)
# print(client.api_key)
# print(client.base_url)

def get_response():
    client = OpenAI(api_key=API_KEY, base_url=BASE_URL)
    completion = client.chat.completions.create(
        model=MODEL_NAME,
        messages=[{'role': 'system', 'content': 'You are a helpful assistant.'},
                  {'role': 'user', 'content': '你是谁？你的开发者是谁？'}]
    )
    print(completion.model_dump_json())


if __name__ == '__main__':
    get_response()
```

正常返回结果应该是
```
{
	"id": "chatcmpl-xxxxxxx",
	"choices": [{
		"finish_reason": "stop",
		"index": 0,
		"logprobs": null,
		"message": {
			"content": "我是一个由OpenAI开发的人工智能助手。我的目的是提供信息和帮助回答问题。我没有特定的个人身份或背景，只是一个用于处理和生成自然语言文本的工具。你有什么具体的问题或需要帮助的地方吗？",
			"role": "assistant",
			"function_call": null,
			"tool_calls": null
		}
	}],
	"created": "xxxxxxx",
	"model": "gpt-4o-2024-05-13",
	"object": "chat.completion",
	"system_fingerprint": "xxxxxxx",
	"usage": {
		"completion_tokens": 53,
		"prompt_tokens": 25,
		"total_tokens": 78
	}
}
```

第二个如果API回复是正常的，但是函数调用部分出了问题，可能需要你提供更详细的反馈信息，比如在94行前面调用print或者pprint输出返回结果等，看是否是OpenAI API返回的 response_message 对象没有 'content' 字段，如果是这个问题的话确定问题出现在哪个环节，以及 'content' 字段在何处变为 null等等。

**Comment by vank3f3** [comment]
感谢回复。再补充一下。
主要是在仓库原始代码中的 main 中，”response_message“的”content“ 为 None，这在 ”client.chat.completions.create()“ 方法中，是不允许的，如图是我原始返回的”response.choices[0].message“。
![image](https://github.com/Huoyuuu/SearchGPT-Explorer/assets/47717461/5205376a-2a45-496f-9b01-433f33a61714)

**Comment by Huoyuuu** [comment]
原来如此，API正常，调用返回正常，是代码处理的方式出了问题。方便提个pr吗？

**Comment by vank3f3** [comment]
献丑了，感谢老哥的开源，function call 很棒的入门引导仓库。
